<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Daftar_kkm_model extends CI_Model
{

    public $table = 'tbl_daftar_kkm';
    public $id = 'no_daftar';
	public $nim = 'nim';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
	
	
	public function view($nim){
			return $this->db->query("SELECT * FROM tbl_daftar_kkm WHERE nim='".$nim."'");  
    }
		
		
		function update_images($nim,$gambar,$gambar,$gambar)
{
$url = 'http://localhost/lppm.uinsgd.ac.id/assets/dokumen-persyaratan/';
$dt = array(

'nama' => $this->input->post('nama'),
		'nim' => $this->input->post('nim'),
		'jenis_kelamin' => $this->input->post('jenis_kelamin'),
		'tempat_tanggal_lahir' => $this->input->post('tempat_tanggal_lahir'),
		'fakultas' => $this->input->post('fakultas'),
		'jurusan' => $this->input->post('jurusan'),
		'semester' => $this->input->post('semester'),
		'alamat_asal' => $this->input->post('alamat_asal'),
		'alamat_sekarang' => $this->input->post('alamat_sekarang'),
		'no_telp' => $this->input->post('no_telp'),
		'keterangan_khusus' => $this->input->post('keterangan_khusus'),
		'id_kelompok' => $this->input->post('id_kelompok'),
		
'photo'=>$url.$gambar[0],
'surat_keterangan_kuliah'=>$url.$gambar[1],
'bukti_lunas_spp'=>$url.$gambar[2]
);
$this->db->where('nim',$nim);
return $this->db->insert('tbl_daftar_kkm',$dt);

}
	
	
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
     function get_by_nim($nim)
    {
	
      	$query = $this->db->query('Select * from tbl_daftar_kkm WHERE tbl_daftar_kkm.nim= "'.$nim.'"');
		return $query;
    } 
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('no_daftar', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nim', $q);
	$this->db->or_like('tempat_tanggal_lahir', $q);
	$this->db->or_like('fakultas', $q);
	$this->db->or_like('jurusan', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('alamat_asal', $q);
	$this->db->or_like('alamat_sekarang', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('keterangan_khusu', $q);
	$this->db->or_like('persyaratan', $q);
	$this->db->or_like('photo_2x3', $q);
	$this->db->or_like('id_kelompok', $q);
	$this->db->or_like('dpl', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_daftar', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nim', $q);
	$this->db->or_like('tempat_tanggal_lahir', $q);
	$this->db->or_like('fakultas', $q);
	$this->db->or_like('jurusan', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('alamat_asal', $q);
	$this->db->or_like('alamat_sekarang', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('keterangan_khusu', $q);
	$this->db->or_like('persyaratan', $q);
	$this->db->or_like('photo_2x3', $q);
	$this->db->or_like('id_kelompok', $q);
	$this->db->or_like('dpl', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Daftar_kkm_model.php */
/* Location: ./application/models/Daftar_kkm_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-03 22:59:22 */
/* http://harviacode.com */